#DAC CONFIG
VREF = 2560 #reference voltage for DAC (mV)

#ADC CONFIG
ADC_OTA1 = 0
ADC_OTA2 = 0
ADC_STARTUP_SEL = 0
ADC_C2 = 0
ADC_MUX = 0

#PSTAT CONFIG
PSTAT_S_BIAS = 0
PSTAT_S_CC = 0
PSTAT_S_OTAW = 0
PSTAT_S_CLSABW = 0
PSTAT_S_OTAR = 0
PSTAT_S_CLSABR = 0
PSTAT_S_SRE = 0
PSTAT_OTAWI2X = 0
PSTAT_OTARI2X = 0
PSTAT_CLSABWI2X = 0
PSTAT_CLSABRI2X = 0

#CC CONFIG
CC_GAIN = 1 #set CC gain. 0-> 10x, 1-> 1x, 2-> 0.1x
CC_SEL = 5
